### PR TITLE
3 new field types

### PR DESCRIPTION
**Pull request by zlorf**
Hi,

I added 3 new Value types (date/time), which I developed for some project.

I also fixed testrunner and setup.py.

BTW: There is a noticable lack of django-dbsettings on Pypi. Would you upload it there, please? Or I can handle this, if you don't mind.

### CODE REVIEW

**Comment by hdg700** [comment]
Hello. I've merged your code.

About Pypi. I have no time for this project now. You may do it yourself, if you want :)

**Comment by zlorf** [comment]
Ok, I'll do this.

**Comment by zlorf** [comment]
Uploaded: http://pypi.python.org/pypi/dbsettings/
I have changed status from Alpha to Beta.

**Comment by zlorf** [comment]
I mean http://pypi.python.org/pypi/django-dbsettings/

**Pull request merged**
